### ISSUE TITLE
TODO: Implement *incepta* pharmaceuticals

### ISSUE THREAD

**Issue by fa7ad** [fa7ad/medicines-crawler#1]
The interface is really similar. 
Each record is under the class `pitem`
Inside that, 
Trade names are `pitem-name` and groups are `pitem-desc`.

I will try to implement whenever I get time but, help is appreciated.

**Comment by fa7ad** [comment]
@porimol can you help with this (and/or other pharmaceutical companies)?

**Comment by porimol** [comment]
Okay, Tonight I will try my best to implement.

Thanks

**Comment by fa7ad** [comment]
@porimol I finished this too :smile: 
You can help with others... I just had some free time
